version: '3.8'

services:
  web:
    build: .
    container_name: crm_django
    restart: always
    volumes:
      - ./db.sqlite3:/usr/src/app/db.sqlite3:rw
      - ./staticfiles:/usr/src/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=CRMdemo.settings
    networks:
      - crm_network

  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/usr/src/app/staticfiles
    depends_on:
      - web
    networks:
      - crm_network

  telegram_bot:
    build: .
    container_name: crm_bot
    restart: always
    command: python manage.py python-telegram-bot
    environment:
      - DJANGO_SETTINGS_MODULE=CRMdemo.settings
    volumes:
      - ./db.sqlite3:/usr/src/app/db.sqlite3:rw
    networks:
      - crm_network

networks:
  crm_network:
    driver: bridge
