version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 CRMdemo.wsgi:application
    volumes:
      - .:/usr/src/app
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - bot

  bot:
    build: .
    command: python manage.py python-telegram-bot
    volumes:
      - .:/usr/src/app
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media