# Generated by Django 5.1.3 on 2025-08-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('payment', 'Оплата'), ('parking', 'Прибытие на парковку'), ('preparation', 'Подготовка к экспорту'), ('bill_of_lading', 'Коносамент'), ('port_transport', 'Транспортировка в порт'), ('port_arrival', 'Прибытие в порт'), ('order_received', 'Заказ получен')], default='payment', max_length=50)),
                ('payment_doc', models.FileField(blank=True, null=True, upload_to='docs/payment/')),
                ('parking_doc', models.FileField(blank=True, null=True, upload_to='docs/parking/')),
                ('preparation_doc', models.FileField(blank=True, null=True, upload_to='docs/preparation/')),
                ('bill_of_lading_doc', models.FileField(blank=True, null=True, upload_to='docs/bill_of_lading/')),
                ('port_transport_doc', models.FileField(blank=True, null=True, upload_to='docs/port_transport/')),
                ('port_arrival_doc', models.FileField(blank=True, null=True, upload_to='docs/port_arrival/')),
                ('order_received_doc', models.FileField(blank=True, null=True, upload_to='docs/order_received/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=100)),
                ('number_order', models.CharField(max_length=100)),
                ('number_note', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.client')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.status_orders')),
            ],
        ),
    ]
