# Generated by Django 5.1.3 on 2025-08-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='bid',
            name='opened_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carsphoto',
            name='checkpoint1',
            field=models.FileField(blank=True, null=True, upload_to='cars_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='carsphoto',
            name='checkpoint2',
            field=models.FileField(blank=True, null=True, upload_to='cars_photos/%Y/%m/%d/'),
        ),
    ]
