# Generated by Django 5.2 on 2025-09-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="url",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Конечная ссылка на авто",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="url_users",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Исходная ссылка на авто",
            ),
        ),
    ]
