# Generated by Django 5.1.3 on 2025-08-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgusers',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
