# Generated by Django 5.1.3 on 2025-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_carsphoto_photo_bid_opened_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsphoto',
            name='checkpoint1',
        ),
        migrations.RemoveField(
            model_name='carsphoto',
            name='checkpoint2',
        ),
        migrations.AddField(
            model_name='bid',
            name='checkpoint1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='checkpoint2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
