# Generated by Django 5.1.3 on 2025-08-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_carsphoto_checkpoint1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsphoto',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='cars_photos/%Y/%m/%d/'),
        ),
    ]
