# Generated by Django 5.1.3 on 2025-08-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_tgusers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='carsphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='carsphoto',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo.bid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsphoto',
            name='file_url',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
