# Generated by Django 5.2 on 2025-09-16 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_alter_bid_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField()),
                ("message_thread_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField()),
                ("user_id", models.BigIntegerField()),
                ("username", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.bid"
                    ),
                ),
            ],
        ),
    ]
