# Generated by Django 5.2 on 2025-09-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0004_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="thread_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
