# Generated by Django 5.1.3 on 2025-08-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_bid_photo_remove_carsphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsphoto',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='demo.bid'),
        ),
    ]
