# Generated by Django 5.1.3 on 2025-08-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_carsphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='checkpoint1',
            new_name='checklist_point1',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='checkpoint2',
            new_name='checklist_point2',
        ),
    ]
