# Generated by Django 5.2 on 2025-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0005_bid_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="to_bot",
            field=models.BooleanField(default=False),
        ),
    ]
