# Generated by Django 5.1.3 on 2025-08-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_rename_checkpoint1_bid_checklist_point1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
    ]
