# Generated by Django 5.1.3 on 2025-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_carsphoto_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsphoto',
            name='file_url',
            field=models.FileField(upload_to='storage/'),
        ),
    ]
