# Generated by Django 5.1.3 on 2025-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_carsphoto_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsphoto',
            name='file_url',
            field=models.FileField(upload_to=''),
        ),
    ]
