# Generated by Django 5.1.3 on 2025-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='arrived_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
