# Generated by Django 5.2 on 2025-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0006_chatmessage_to_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="topic_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
