# Generated by Django 5.1.3 on 2025-08-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_alter_carsphoto_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='checklist_point1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Состояние бампера'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='checklist_point2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень топлива в баке'),
        ),
    ]
