# Generated by Django 5.1.3 on 2025-08-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_bid_arrived_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='arrived_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
