# Generated by Django 5.2 on 2025-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0008_chatmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
