# Generated by Django 5.1.3 on 2025-08-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_bid_arrived_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='url',
            new_name='url_users',
        ),
    ]
