# Generated by Django 5.1.3 on 2025-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_bid_checklist_point1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='OGRN',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН компании'),
        ),
        migrations.AddField(
            model_name='companies',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
