# Generated by Django 5.1.3 on 2025-08-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_rename_url_bid_url_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='url_manager',
            new_name='url',
        ),
    ]
