# Generated by Django 5.1.3 on 2025-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_companies_ogrn_companies_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Авто в наличии'),
        ),
    ]
