# Generated by Django 5.1.3 on 2025-08-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_rename_url_manager_bid_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
