# Generated by Django 5.1.3 on 2025-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_bid_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusers',
            name='is_caller',
            field=models.BooleanField(default=0),
        ),
    ]
