# Generated by Django 5.1.3 on 2025-09-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_tgusers_is_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='calls_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
