# Generated by Django 5.1.3 on 2025-08-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_dealers_company_name_alter_dealers_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chats',
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
