# Generated by Django 5.1.3 on 2025-09-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_groups_calls_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='caller_saw',
            field=models.BooleanField(default=False, verbose_name='Отправлено в чат просмотрщиков'),
        ),
    ]
