# Generated by Django 5.1.3 on 2025-08-22 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_alter_carsphoto_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.companies', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Исполняющий менеджер'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.dealers', verbose_name='Дилер'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='drive_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='demo.carsphoto', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='power',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='transmission',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка менеджера'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='url_users',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка пользователя'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
