# Generated by Django 5.1.3 on 2025-08-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_alter_bid_brand_alter_bid_company_alter_bid_deadline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusfile',
            options={'verbose_name': 'Файл к статусам', 'verbose_name_plural': 'Файлы к статусам'},
        ),
    ]
