# Generated by Django 5.1.3 on 2025-08-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_alter_statusfile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон компании'),
        ),
    ]
