# Generated by Django 5.1.3 on 2025-08-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_alter_dealers_address_alter_dealers_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='companies',
            name='INN',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН компании'),
        ),
        migrations.AddField(
            model_name='companies',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='companies',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код присоединения к компании'),
        ),
        migrations.AddField(
            model_name='companies',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.companies'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='client', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
