# Generated by Django 5.1.3 on 2025-08-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_remove_user_telegram_id_companies_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
