# Generated by Django 5.1.3 on 2025-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_companies_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
