# Generated by Django 5.1.3 on 2025-08-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_remove_user_company_user_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_company',
            options={'verbose_name': 'Сотрудник компании', 'verbose_name_plural': 'Сотрудники компании'},
        ),
        migrations.AlterModelTable(
            name='user_company',
            table='user_company',
        ),
    ]
