# Generated by Django 5.1.3 on 2025-08-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_alter_user_company_options_alter_user_company_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО пользователя'),
        ),
    ]
