# Generated by Django 5.1.3 on 2025-08-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_remove_user_role_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_company',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
