# Generated by Django 5.1.3 on 2025-08-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_alter_user_company_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
