# Generated by Django 5.1.3 on 2025-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0025_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='client', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
