# Generated by Django 5.1.3 on 2025-08-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Исполняющий менеджер'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
