# Generated by Django 5.1.3 on 2025-08-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0027_alter_bid_deadline_alter_bid_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('disable', 'Disable'), ('open', 'Open')], default='disable', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
