# Generated by Django 5.1.3 on 2025-08-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_alter_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='shown_to_bot',
            field=models.BooleanField(default=False, verbose_name='Уведомление боту показано'),
        ),
    ]
