# Generated by Django 5.1.3 on 2025-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0030_alter_user_company_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_company',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер'), ('leading_manager', 'Ведущий менеджер'), ('logist', 'Логист')], default='manager', max_length=100),
        ),
    ]
