# Generated by Django 5.1.3 on 2025-08-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0031_alter_user_company_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование компании(обязательно)'),
        ),
    ]
