# Generated by Django 5.1.3 on 2025-08-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_alter_dealers_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='company_name',
            field=models.CharField(default='lallaa', max_length=100, verbose_name='Наименование компании(обязательно)'),
            preserve_default=False,
        ),
    ]
