# Generated by Django 5.1.3 on 2025-08-25 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0033_alter_dealers_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Конечная ссылка на авто'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='url_users',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Исходная ссылка на авто'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
